// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQHpr31I7Ari8eptYbcFuNzvYHCq4SeBk',
    appId: '1:921126696949:web:cfd7c3cabee826d80952bc',
    messagingSenderId: '921126696949',
    projectId: 'coffee-shop-2d9a0',
    authDomain: 'coffee-shop-2d9a0.firebaseapp.com',
    storageBucket: 'coffee-shop-2d9a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlo8HNEUAHwH8d5tLTBydRyBmywpdpqWc',
    appId: '1:921126696949:android:ec570b9644d498c10952bc',
    messagingSenderId: '921126696949',
    projectId: 'coffee-shop-2d9a0',
    storageBucket: 'coffee-shop-2d9a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpexsw1g1P-o61pPHP1R77JQ9RwlCzdtE',
    appId: '1:921126696949:ios:68de35d9690c96470952bc',
    messagingSenderId: '921126696949',
    projectId: 'coffee-shop-2d9a0',
    storageBucket: 'coffee-shop-2d9a0.appspot.com',
    iosBundleId: 'com.example.coffeeshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpexsw1g1P-o61pPHP1R77JQ9RwlCzdtE',
    appId: '1:921126696949:ios:66d502c37595cbbc0952bc',
    messagingSenderId: '921126696949',
    projectId: 'coffee-shop-2d9a0',
    storageBucket: 'coffee-shop-2d9a0.appspot.com',
    iosBundleId: 'com.example.coffeeshop.RunnerTests',
  );
}
